### ISSUE TITLE
[wearable] Presentation Views -> List -> Main + SubText

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1051]

**Comment by grzegorz-czajkowski** [comment]
Patch merged. Issue can be closed.

**Comment by lslachciak** [comment]
In order to access Main + Sub text example you need to go
Presentation View --> List --> **SubText** --> **SubText**
I think we shouldn't duplicate Subtext menu.
How about 
Presentation View --> List --> **Main** --> **SubText**

**Comment by grzegorz-czajkowski** [comment]
SubText has 4 examples:
 - Sub text
 - Sub text (editable)
 - Sub text max (fade on right) https://github.com/Samsung/TAU/issues/1052
 - Sub text max (fade on left) https://github.com/Samsung/TAU/issues/1052

That's why I created separated menu for future implementation, also added comment in the code for this 
https://github.com/Samsung/TAU/blob/c322e506039bac5544059cd3113ee1a29fb191ce/examples/wearable/UIComponents/contents/presentation-views/list/sub-text/index.html#L32

**Comment by lslachciak** [comment]
I'll prepare PR with new concept of menus
