### ISSUE TITLE
 [wearable] Presentation View -> List -> Icon ->Right

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1057]

**Comment by grzegorz-czajkowski** [comment]
Patch merged. Issue can be closed.

**Comment by lslachciak** [comment]
@grzegorz-czajkowski would it be possible to use icons as in example
examples/wearable/UIComponents/contents/presentation-views/list/list-button/three-buttons.html
rather than squares.
Those sqares doesn't look nice for examples

See:
![Screenshot from 2020-05-18 13-29-10](https://user-images.githubusercontent.com/2246331/82208401-bf378c00-990b-11ea-90d3-42470b2a09bc.png)
vs
![Screenshot from 2020-05-18 13-30-14](https://user-images.githubusercontent.com/2246331/82208412-c199e600-990b-11ea-93f2-49333a96975c.png)

**Comment by grzegorz-czajkowski** [comment]
@lslachciak ok I will use different button. This square button was used in guide.

**Comment by grzegorz-czajkowski** [comment]
@lslachciak 
Changed the square icon. Result
![Screenshot from 2020-05-20 07-59-49](https://user-images.githubusercontent.com/46523330/82410529-62a1b180-9a70-11ea-84ed-1329e200ef3c.png)

However, to provide the same effect as in "Button List" examples (pink color and border radius) we would have to:
 - deliver such icon (as png for example) 
 - add style inline to each element since delivering such style as inline class (in HTML) or external (in app style.css) results in overriding them by tau.css

**Comment by lslachciak** [comment]
I think this is enough what we have now in https://github.com/Samsung/TAU/pull/1107

**Comment by grzegorz-czajkowski** [comment]
Fix applied issue can be closed.

**Comment by lslachciak** [comment]
thank you
