### ISSUE TITLE
ui-view-switcher: no example in UIComonents

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#203]
No example for 
https://developer.tizen.org/development/api-references/web-application?redirect=https://developer.tizen.org/dev-guide/5.0.0/org.tizen.web.apireference/html/ui_fw_api/Wearable_UIComponents/wearable_viewSwitcher.htm

**Comment by pkaczmarczy** [comment]
I did not found corresponding widget in guidelines.

I have run example from documentation and it look like this: (I have run this with rectangular stylesheet - this widget does not have circular stylesheet implemented):

![Screenshot from 2019-08-13 13-06-43](https://user-images.githubusercontent.com/38784474/62936954-6a3e7680-bdcb-11e9-90fa-e3110abf3411.png)

With short text:
![Screenshot from 2019-08-13 12-46-56](https://user-images.githubusercontent.com/38784474/62936965-71658480-bdcb-11e9-9e25-bda8872ef6a0.png)

With longer text:
![Screenshot from 2019-08-13 12-47-16](https://user-images.githubusercontent.com/38784474/62936973-7aeeec80-bdcb-11e9-89c4-65b5ae442f59.png)

With images: 
![Screenshot from 2019-08-13 12-57-20](https://user-images.githubusercontent.com/38784474/62936979-7de9dd00-bdcb-11e9-8423-68b24b6c54c6.png)

Dear @lslachciak Please share your opinion about this widget. Because of it's not mentioned in any guideline I think it should not be mentioned in documentation or it should be marked as deprecated and we do not recommend to use it.

For navigating between pages there is a section changer widget and for displaying images on carousel we provide coverflow widget.

**Comment by lslachciak** [comment]
Because this is not a part of guidelines for 4.0/5.0 I think we should remove it from doc.
Could you prepare PR removing this site from documentation?

**Comment by pkaczmarczy** [comment]
PR: https://github.com/Samsung/tizen-docs/pull/804
I am not able to add you as reviewers to this PR.

**Comment by lslachciak** [comment]
Since Tizen 5.0, --> Since Tizen 4.0,

**Comment by pkaczmarczy** [comment]
The https://github.com/Samsung/tizen-docs/pull/804 has been already merged into tizen-docs repository
