### ISSUE TITLE
Radio list not working (old item remains selected & new item loses selection after scrolling)

### ISSUE THREAD

**Issue by jokrzeja** [Samsung/TAU#458]
Radio list selection is not deselecting old element if new element is farther than 3rd element on the list (and invisible - you can only see 3 list elements at a time).

How to reproduce:
1. Create new sample project in Tizen Studio: New project > sample > wearable v4.0 > web application > UI >  TAU UI Components (sample version 1.4.55)

2. Run app in emulator and go to: controls > radio.

3. You will see: "screen timeout", radio list selected at "5 seconds" (first item) per default.

4. Scroll to item "30 seconds" and select. At this moment item "5 seconds" is invisible.

5. Scroll up to item "5 seconds". It is still selected. (It shouldn't be!)

6. Scroll down to item "30 seconds" which you selected in step 4. It is not selected. (It should be!)

Further anomalies..:
If you do this with item "1 minute" or "5 minutes", then both ("5 seconds" & "1 minute" OR "5 seconds" & "5 minute") remain selected.

I hope you can fix this as soon as possible, this is a very basic functionality.

**Comment by grzegorz-czajkowski** [comment]
Under investigations of building carousel from list items and drawing them. We probably have to resign from current approach of detaching carousel elements from DOM and try to make them invisible so radio buttons will be toggled automatically. 
This requires understanding whole arcListView logic including separators (group index and dividers).

**Comment by grzegorz-czajkowski** [comment]
In UIComponets app, ArcListview has at most three elements in three. Those elements are dynamically added/removed depending on scroll position.
If *selected* element goes out of screen - it's being removed form tree. Let's assume that new element is selected. Then we come back to previous scroll position. A removed element is added to tree again. Since it was in *selected* state, latest selected element losses selection and selection is added to old radio button.

Maybe we should de-select radio button from removed element if new element was selected. This will probably fix radio button case. I will think of this deeper.

**Comment by grzegorz-czajkowski** [comment]
We could mark removed element as invalid and while adding it again, we should verify if different radio element from the same group is already selected. If yes, we should de-select element being added to DOM.

**Comment by lslachciak** [comment]
Ok, for me, but please consider also other possible solution - when selecting element marking other elements in TAU memory unselected, browser is already doing this for elements in DOM, so why TAU shouldn't do this for elements in memory?

**Comment by grzegorz-czajkowski** [comment]
Patch has been merged.
