### ISSUE TITLE
UIComponents App - scroller not disappearing

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#563]
In UIComponents app scroller sometimes is not disappearing after entering menu option or going back to the higher level.

![20200129_082207](https://user-images.githubusercontent.com/2246331/73336007-002e6680-4271-11ea-9e02-380ab81372fc.jpg)
See attached video:
[scroller_issue.zip](https://github.com/Samsung/TAU/files/4126719/scroller_issue.zip)

**Comment by lslachciak** [comment]
Reproduction on device
UIComponents-->List-->Normal List -->back --> Normal List -- scrollbar not disappearing

**Comment by lslachciak** [comment]
In src/css/profile/wearable/changeable/common/layout.less
.ui-page.ui-scroll-on {
	.ui-scroller {
		overflow-y: auto;
}
this property makes problems
Updated: after futher checks - no control from TAU side possible

**Comment by lslachciak** [comment]
this issue is strictly connected with build-in feature of web engine scroller.
According to the checks on sample app its behaviour is following - when scroll event occurs scrollbar disappears,
also when content change is done also scrollbar disappears.
In case of UIComponent app scrollbar stays visible so couldn't find proof that this isssue is web engine specific

**Comment by lslachciak** [comment]
According to the further checks, there TAU is not modifying scrollbar visibility.
This is web engine which shows and hides scrollbar. Not hiding scrollbar by web engine may be related to missing some events. At this moment don't see issue on TAU side.
