### ISSUE TITLE
5. Etc - End effect

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#629]
Implement end effect according to the guidelines

**Comment by grzegorz-czajkowski** [comment]
Added support for using Bouncing widget with both directions Vertical and Horizontal. Exposed additional API to easy show bouncing effect instead of using drag() API.
Used this API in ArcListView - feature works fine.
Need to find a way to use drag() method for both directions or change widgets that are using Bouncing widget (like SectionChanger, Scroller, VirtualList) to use new API.

**Comment by DevronB** [comment]
In addition to this, the bouncing effects at the end of lists, sections changers etc. when scrolling with drag or rotary bezel on wearable does not have the vibration feedback as it does in native.

**Comment by grzegorz-czajkowski** [comment]
@DevronB 
Thanks for your comment. We will consider this as separate issue - https://github.com/Samsung/TAU/issues/667

**Comment by grzegorz-czajkowski** [comment]
Main patches landed.  Follow up: https://github.com/Samsung/TAU/issues/677
Issue can be closed.
